export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_CLEAR = "LOGIN_CLEAR";


export const OTP_INIT = "OTP_INIT";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAIL = "OTP_FAIL";
export const OTP_CLEAR = "OTP_CLEAR";


export const GET_BATCH = "GET_BATCH";
export const BATCH_SUCCESS = "BATCH_SUCCESS";
export const BATCH_UPDATE = "BATCH_UPDATE";
export const BATCH_FAIL = "BATCH_FAIL";
export const BATCH_CLEAR = "BATCH_CLEAR";


export const STARTWORK_INIT = "STARTWORK_INIT";
export const STARTWORK_SUCCESS = "STARTWORK_SUCCESS";
export const STARTWORK_FAIL = "STARTWORK_FAIL";
export const STARTWORK_CLEAR = "STARTWORK_CLEAR";

export const ENDWORK_INIT = "ENDWORK_INIT";
export const ENDWORK_SUCCESS = "ENDWORK_SUCCESS";
export const ENDWORK_FAIL = "ENDWORK_FAIL";
export const ENDWORK_CLEAR = "ENDWORK_CLEAR";

export const SHIPMENTOTP_INIT = "SHIPMENTOTP_INIT";
export const SHIPMENTOTP_SUCCESS = "SHIPMENTOTP_SUCCESS";
export const SHIPMENTOTP_FAIL = "SHIPMENTOTP_FAIL";
export const SHIPMENTOTP_CLEAR = "SHIPMENTOTP_CLEAR";

export const DELIVERD_INIT = "DELIVERD_INIT";
export const DELIVERD_SUCCESS = "DELIVERD_SUCCESS";
export const DELIVERD_FAIL = "DELIVERD_FAIL";
export const DELIVERD_CLEAR = "DELIVERD_CLEAR";

export const CANCELLED_INIT = "CANCELLED_INIT";
export const CANCELLED_SUCCESS = "CANCELLED_SUCCESS";
export const CANCELLED_FAIL = "CANCELLED_FAIL";
export const CANCELLED_CLEAR = "CANCELLED_CLEAR";

export const RESCHEDULED_INIT = "RESCHEDULED_INIT";
export const RESCHEDULED_SUCCESS = "RESCHEDULED_SUCCESS";
export const RESCHEDULED_FAIL = "RESCHEDULED_FAIL";
export const RESCHEDULED_CLEAR = "RESCHEDULED_CLEAR";

export const REFUSED_INIT = "REFUSED_INIT";
export const REFUSED_SUCCESS = "REFUSED_SUCCESS";
export const REFUSED_FAIL = "REFUSED_FAIL";
export const REFUSED_CLEAR = "REFUSED_CLEAR";

export const COMPLETEBATCH_INIT = "COMPLETEBATCH_INIT";
export const COMPLETEBATCH_SUCCESS = "COMPLETEBATCH_SUCCESS";
export const COMPLETEBATCH_FAIL = "COMPLETEBATCH_FAIL";
export const COMPLETEBATCH_CLEAR = "COMPLETEBATCH_CLEAR";
export const COMPLETEBATCH_UPDATE = "COMPLETEBATCH_UPDATE";

export const SENDWPSMS_INIT = "SENDWPSMS_INIT";
export const SENDWPSMS_SUCCESS = "SENDWPSMS_SUCCESS";
export const SENDWPSMS_FAIL = "SENDWPSMS_FAIL";
export const SENDWPSMS_CLEAR = "SENDWPSMS_CLEAR";

export const WPCUSTOMEROTP_INIT = "WPCUSTOMEROTP_INIT";
export const WPCUSTOMEROTP_SUCCESS = "WPCUSTOMEROTP_SUCCESS";
export const WPCUSTOMEROTP_FAIL = "WPCUSTOMEROTP_FAIL";
export const WPCUSTOMEROTP_CLEAR = "WPCUSTOMEROTP_CLEAR";

export const REFUSE_REASON_INIT = "REFUSE_REASON_INIT";
export const REFUSE_REASON_SUCCESS = "REFUSE_REASON_SUCCESS";
export const REFUSE_REASON_FAIL = "REFUSE_REASON_FAIL";
export const REFUSE_REASON_CLEAR = "REFUSE_REASON_CLEAR";

export const THEME = "THEME";